version: '2'
services:
    hospital-app:
        image: hospital
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hospital-mysql:3306/hospital?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hospital-mysql:
        extends:
            file: mysql.yml
            service: hospital-mysql
